name: Update

on:
  push:
    branches: [ main ]
  schedule:
  - cron: "0 18 * * *"
    

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Download repo
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ^1.15

    - name: Runnning generation script
      shell: bash
      run: |
        bash ./generate.sh
      continue-on-error: true
      
